### ISSUE TITLE
Check-mode fails at the step "Create persistence file"

### ISSUE THREAD

**Issue by falstaff1288** [cloudalchemy/ansible-pushgateway#35]
**What happened?**
When running in check-mode, the role fails at the step "Create persistence file"
**Did you expect to see some different?**
This step shouldn't fail.
**How to reproduce it (as minimally and precisely as possible)**:
Run the role in check_mode

**Environment**
Fedora 31

* Role version:
Commit 66993dfd

* Ansible version information:
ansible==2.9.7

* Variables:

```
pushgateway_version: 1.2.0
```

* Ansible playbook execution Logs:
```
< TASK [ansible-pushgateway : Create persistence file] >
 ------------------------------------------------------
task path: prometheus/roles/ansible-pushgateway/tasks/configure.yml:11
fatal: [telemetrydemo]: FAILED! => 
  msg: 'The conditional check ''touch_log.diff.before.state != "file"'' failed. The error was: error while evaluating conditional (touch_log.diff.before.state != "file"): ''dict object'' has no attribute ''diff'''
```

**Anything else we need to know?**:
Thanks for the good work!

**Comment by chrs4711** [comment]
Can confirm.

* Controller: macOS Big Sur
* Target: Ubuntu 18.04.4 LTS
* Ansible version: ansible-playbook [core 2.12.1]
* Role version: 0.2.3, 0.2.4

The problem seems to be related to the usage of the `changed_when` conditional, which takes the result of the file module into consideration once it has run.

According to the [documentation of the file module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-state) using `state=touched` always results in a change to the target file anyway, so perhaps this conditional can be removed.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
